### ISSUE TITLE
为什么用开发版的一直403，用了商业版的一下就好了

### ISSUE THREAD

**Issue by LucyChao233** [kexue-z/nonebot-plugin-heweather#10]
rt

**Comment by kexue-z** [comment]
请检查和风天气相关错误 与本插件无关
区分开发版和商业版APIkey 并设置好配置
会有log提示是使用什么版本的key

**Comment by kexue-z** [comment]
升级个人开发版可以使用 7日 预报
普通只能用 3日预报

**Comment by LucyChao233** [comment]
> 升级个人开发版可以使用 7日 预报 普通只能用 3日预报

是商业版可以用7日吧。。另外您插件是不是默认调取七日预报，而免费的只能三日的导致403？。。。

**Comment by kexue-z** [comment]
确实 在改了
