### ISSUE TITLE
您的插件TLE了。。。

### ISSUE THREAD

**Issue by LucyChao233** [kexue-z/nonebot-plugin-heweather#11]
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
setting frame content, waiting until "networkidle"
============================================================

**Comment by kexue-z** [comment]
可能是生成图片图片的时候出现了问题
建议检查一下代理为关闭或国内代理

--------------原始邮件--------------
发件人："863109569 ***@***.***&gt;;
发送时间：2022年1月23日(星期天) 中午1:58
收件人："kexue-z/nonebot-plugin-heweather" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[kexue-z/nonebot-plugin-heweather] 您的插件TLE了。。。 (Issue #11)
-----------------------------------

 

 
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
 =========================== logs ===========================
 setting frame content, waiting until "networkidle"
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by insomniaaac** [comment]
请问一下，如果部署在云服务器上，仍然出现这个问题怎么办？（报错信息和楼主一致）

**Comment by LucyChao233** [comment]
> 请问一下，如果部署在云服务器上，仍然出现这个问题怎么办？（报错信息和楼主一致）

我的也是部署在云服务器上，偶尔会有tle的情况

**Comment by kexue-z** [comment]
考虑使用svg格式读取天气图片 等更新（最近加班没时间）~~最好PR~~

**Comment by jcjrobert** [comment]
把timeout设置长点就行了，就第一次生成会慢些（x
