### ISSUE TITLE
能成功获取天气数据但是最后生成的时候报错？

### ISSUE THREAD

**Issue by LeonX86** [kexue-z/nonebot-plugin-heweather#14]
2-17 23:22:44 [DEBUG] nonebot | Stop event propagation
02-17 23:23:05 [SUCCESS] nonebot | ONEBOT V11 1851377216 | [message.private.friend]: Message -181963694 from 1843164971 "无锡天气"
02-17 23:23:05 [DEBUG] nonebot | Checking for matchers in priority 1...
02-17 23:23:05 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
02-17 23:23:05 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False>
02-17 23:23:05 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False>
02-17 23:23:05 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x7f16e1dc4280>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=MessageEvent, required=True)], parameterless=[]>
02-17 23:23:05 [INFO] nonebot_plugin_heweather | 使用个人开发版API
02-17 23:23:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'location': [{'name': '无锡', 'id': '101190201', 'lat': '31.57473', 'lon': '120.30166', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '15', 'fxLink': 'http://hfx.link/30p1'}, {'name': '江阴', 'id': '101190202', 'lat': '31.91098', 'lon': '120.27589', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '23', 'fxLink': 'http://hfx.link/30q1'}, {'name': '宜兴', 'id': '101190203', 'lat': '31.36438', 'lon': '119.82054', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '25', 'fxLink': 'http://hfx.link/30r1'}, {'name': '滨湖', 'id': '101190206', 'lat': '31.55022', 'lon': '120.26605', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '25', 'fxLink': 'http://hfx.link/1tu91'}, {'name': '惠山', 'id': '101190205', 'lat': '31.68101', 'lon': '120.30354', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '35', 'fxLink': 'http://hfx.link/1tu81'}, {'name': '锡山', 'id': '101190204', 'lat': '31.58556', 'lon': '120.35730', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '35', 'fxLink': 'http://hfx.link/30s1'}, {'name': '梁溪', 'id': '101190207', 'lat': '31.57570', 'lon': '120.29659', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '35', 'fxLink': 'http://hfx.link/1tua1'}, {'name': '新吴', 'id': '101190208', 'lat': '31.55096', 'lon': '120.35278', 'adm2': '无锡', 'adm1': '江苏省', 'country': '中国', 'tz': 'Asia/Shanghai', 'utcOffset': '+08:00', 'isDst': '0', 'type': 'city', 'rank': '35', 'fxLink': 'http://hfx.link/1tub1'}], 'refer': {'sources': ['QWeather'], 'license': ['commercial license']}}
02-17 23:23:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-17T22:58+08:00', 'fxLink': 'http://hfx.link/30p4', 'now': {'pubTime': '2022-02-17T22:00+08:00', 'aqi': '28', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '28', 'pm2p5': '17', 'no2': '33', 'so2': '5', 'co': '0.6', 'o3': '43'}, 'station': [{'pubTime': '2022-02-17T22:00+08:00', 'name': '华庄', 'id': 'CNA3428', 'aqi': '39', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '39', 'pm2p5': '21', 'no2': '29', 'so2': '8', 'co': '0.7', 'o3': '37'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '堰桥', 'id': 'CNA1195', 'aqi': '24', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '24', 'pm2p5': '14', 'no2': '22', 'so2': '6', 'co': '0.7', 'o3': '57'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '荣巷', 'id': 'CNA1194', 'aqi': '19', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '19', 'pm2p5': '12', 'no2': '34', 'so2': '5', 'co': '0.4', 'o3': '43'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '东亭', 'id': 'CNA1192', 'aqi': '22', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '22', 'pm2p5': '12', 'no2': '26', 'so2': '5', 'co': '0.6', 'o3': '49'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '漆塘', 'id': 'CNA1191', 'aqi': '27', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '27', 'pm2p5': '17', 'no2': '26', 'so2': '6', 'co': '0.6', 'o3': '51'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '曹张', 'id': 'CNA1190', 'aqi': '25', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '18', 'pm2p5': '17', 'no2': '33', 'so2': '7', 'co': '0.5', 'o3': '43'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '黄巷', 'id': 'CNA1189', 'aqi': '53', 'level': '2', 'category': '良', 'primary': 'PM10', 'pm10': '55', 'pm2p5': '22', 'no2': '64', 'so2': '4', 'co': '0.5', 'o3': '19'}, {'pubTime': '2022-02-17T22:00+08:00', 'name': '雪浪', 'id': 'CNA1188', 'aqi': '27', 'level': '1', 'category': '优', 'primary': 'NA', 'pm10': '27', 'pm2p5': '12', 'no2': '30', 'so2': '4', 'co': '0.7', 'o3': '45'}], 'refer': {'sources': ['QWeather', 'CNEMC'], 'license': ['no commercial use']}}
02-17 23:23:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-17T23:17+08:00', 'fxLink': 'http://hfx.link/30p1', 'now': {'obsTime': '2022-02-17T23:10+08:00', 'temp': '1', 'feelsLike': '-2', 'icon': '104', 'text': '阴', 'wind360': '90', 'windDir': '东风', 'windScale': '2', 'windSpeed': '9', 'humidity': '100', 'precip': '0.5', 'pressure': '1029', 'vis': '4', 'cloud': '100', 'dew': '-1'}, 'refer': {'sources': ['QWeather', 'NMC', 'ECMWF'], 'license': ['no commercial use']}}
02-17 23:23:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-17T22:35+08:00', 'fxLink': 'http://hfx.link/30p1', 'daily': [{'fxDate': '2022-02-17', 'sunrise': '06:39', 'sunset': '17:47', 'moonrise': '18:20', 'moonset': '07:43', 'moonPhase': '满月', 'moonPhaseIcon': '804', 'tempMax': '4', 'tempMin': '1', 'iconDay': '400', 'textDay': '小雪', 'iconNight': '404', 'textNight': '雨夹雪', 'wind360Day': '65', 'windDirDay': '东北风', 'windScaleDay': '3-4', 'windSpeedDay': '19', 'wind360Night': '90', 'windDirNight': '东风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '83', 'precip': '0.8', 'pressure': '1026', 'vis': '24', 'cloud': '38', 'uvIndex': '1'}, {'fxDate': '2022-02-18', 'sunrise': '06:39', 'sunset': '17:48', 'moonrise': '19:21', 'moonset': '08:13', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '5', 'tempMin': '2', 'iconDay': '305', 'textDay': '小雨', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '90', 'windDirDay': '东风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '0', 'windDirNight': '北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '89', 'precip': '2.3', 'pressure': '1027', 'vis': '20', 'cloud': '63', 'uvIndex': '1'}, {'fxDate': '2022-02-19', 'sunrise': '06:38', 'sunset': '17:49', 'moonrise': '20:21', 'moonset': '08:43', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '7', 'tempMin': '-1', 'iconDay': '101', 'textDay': '多云', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '0', 'windDirDay': '北风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '0', 'windDirNight': '北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '44', 'precip': '0.0', 'pressure': '1032', 'vis': '24', 'cloud': '25', 'uvIndex': '1'}, {'fxDate': '2022-02-20', 'sunrise': '06:37', 'sunset': '17:49', 'moonrise': '21:23', 'moonset': '09:14', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '6', 'tempMin': '-2', 'iconDay': '101', 'textDay': '多云', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '0', 'windDirDay': '北风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '135', 'windDirNight': '东南风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '41', 'precip': '0.0', 'pressure': '1032', 'vis': '25', 'cloud': '25', 'uvIndex': '5'}, {'fxDate': '2022-02-21', 'sunrise': '06:35', 'sunset': '17:50', 'moonrise': '22:25', 'moonset': '09:47', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '7', 'tempMin': '-1', 'iconDay': '101', 'textDay': '多云', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '225', 'windDirDay': '西南风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '180', 'windDirNight': '南风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '68', 'precip': '0.0', 'pressure': '1034', 'vis': '25', 'cloud': '24', 'uvIndex': '5'}, {'fxDate': '2022-02-22', 'sunrise': '06:34', 'sunset': '17:51', 'moonrise': '23:31', 'moonset': '10:24', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '8', 'tempMin': '1', 'iconDay': '101', 'textDay': '多云', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '225', 'windDirDay': '西南风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '45', 'windDirNight': '东北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '63', 'precip': '0.0', 'pressure': '1032', 'vis': '25', 'cloud': '25', 'uvIndex': '2'}, {'fxDate': '2022-02-23', 'sunrise': '06:33', 'sunset': '17:52', 'moonrise': '00:00', 'moonset': '10:24', 'moonPhase': '亏凸月', 'moonPhaseIcon': '805', 'tempMax': '6', 'tempMin': '-2', 'iconDay': '101', 'textDay': '多云', 'iconNight': '151', 'textNight': '多云', 'wind360Day': '45', 'windDirDay': '东北风', 'windScaleDay': '1-2', 'windSpeedDay': '3', 'wind360Night': '45', 'windDirNight': '东北风', 'windScaleNight': '1-2', 'windSpeedNight': '3', 'humidity': '74', 'precip': '0.0', 'pressure': '1029', 'vis': '25', 'cloud': '25', 'uvIndex': '1'}], 'refer': {'sources': ['QWeather', 'NMC', 'ECMWF'], 'license': ['no commercial use']}}
02-17 23:23:05 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-02-17T23:23+08:00', 'fxLink': 'http://hfx.link/30p5', 'warning': [], 'refer': {'sources': ['12379'], 'license': ['no commercial use']}}
02-17 23:23:05 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> running complete
02-17 23:23:05 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "bot.py", line 53, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 300, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 232, in run
    uvicorn.run(
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 158, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 207, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/matcher.py", line 742, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/matcher.py", line 709, in simple_run
    await handler(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 76, in __call__
    return await self.call(**values)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_heweather/__init__.py", line 35, in _
    img = await render(w_data)
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/date_source.py", line 158, in html_to_pic
    async with get_new_page(**kwargs) as page:
  File "/usr/local/python3/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 46, in get_new_page
    page = await browser.new_page(**kwargs)
TypeError: new_page() got an unexpected keyword argument 'base_url'

**Comment by kexue-z** [comment]
查询一下`nonebot_plugin_heweather` 和 `nonebot_plugin_htmlrender` 的版本

**Comment by kexue-z** [comment]
经过测试
在 docker 中使用 `python:3.10`
```
nonebot-adapter-onebot    2.0.0b1 
nonebot-plugin-heweather  0.5.2
nonebot-plugin-htmlrender 0.0.4.4
nonebot2                  2.0.0b2
```
测试通过

**Comment by LeonX86** [comment]
> 

重新全部更新了一下，发送信息是正常了，但是图片里所有的文字都是框框
Python3.8.1
nonebot-adapter-onebot    2.0.0b1 
nonebot-plugin-heweather  0.5.1
nonebot-plugin-htmlrender 0.0.4.2
nonebot2                  2.0.0b1

**Comment by kexue-z** [comment]
缺少中文字体

**Comment by LeonX86** [comment]
好的，非常感谢

**Comment by LeonX86** [comment]
今天更新之后又报错了
 'NMC', 'ECMWF'], 'license': ['no commercial use']}}
03-16 00:27:27 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-03-15T23:59+08:00', 'fxLink': 'http://hfx.link/1tqd4', 'now': {'pubTime': '2022-03-15T23:00+08:00', 'aqi': '141', 'level': '3', 'category': '轻度污染', 'primary': 'PM10', 'pm10': '231', 'pm2p5': '62', 'no2': '100', 'so2': '13', 'co': '1.4', 'o3': '12'}, 'refer': {'sources': ['QWeather', 'CNEMC'], 'license': ['no commercial use']}}
03-16 00:27:27 [DEBUG] nonebot_plugin_heweather | {'code': '200', 'updateTime': '2022-03-16T00:27+08:00', 'fxLink': 'http://hfx.link/1tqd5', 'warning': [{'id': '10112011120220315153000917012661', 'sender': '济南市气象台', 'pubTime': '2022-03-15T15:30+08:00', 'title': '济南市气象台发布寒潮黄色预警[III级/较重]', 'startTime': '2022-03-15T15:30+08:00', 'endTime': '2022-03-16T15:30+08:00', 'status': 'active', 'level': '黄色', 'type': '1005', 'typeName': '寒潮', 'text': '济南市气象台2022年03月15日15时30分发布寒潮黄色预警信号：受强冷空气影响，预计16～19日我市将出现寒潮天气。16日开始气温持续下降，过程降温幅度10～12℃。19日早晨气温降至最低，济阳、商河及山区-5℃左右，市区及其它区县-3℃，20日气温缓慢回升。16日白天到17日夜间东北风4～5级阵风7～8级。此外，16日夜间到17日中午有小雨，17日下午到18日中午有雨夹雪。', 'related': '', 'urgency': '', 'certainty': ''}, {'id': '10112011120220315113200174628463', 'sender': '山东省气象台', 'pubTime': '2022-03-15T11:32+08:00', 'title': '山东省气象台发布寒潮蓝色预警[Ⅳ/一般]', 'startTime': '2022-03-15T11:32+08:00', 'endTime': '2022-03-17T11:33+08:00', 'status': 'active', 'level': '蓝色', 'type': '1005', 'typeName': '寒潮', 'text': '山东省气象台于3月15日11时发布寒潮蓝色预警信号：预计16～20日，受强冷空气影响，我省将出现寒潮天气，气温持续下降，16～17日北风风力较大。过程降温幅度：鲁西北、鲁中和鲁南地区10～12℃，半岛地区6～8℃；19～20日早晨最低气温：鲁西北和鲁中地区-8～-4℃，其他地区-3～-1℃。16日凌晨开始至17日夜间，东北风，渤海、渤海海峡、黄海北部和中部7～8级阵风9～10级，内陆地区5～6级阵风7～8级。另外，16～17日，鲁南地区有小到中雨，其他地区有小雨转雨夹雪或小雪。18～19日，全省大部地区有小雨雪。', 'related': '', 'urgency': '', 'certainty': ''}], 'refer': {'sources': ['12379'], 'license': ['no commercial use']}}
03-16 00:27:27 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> running complete
03-16 00:27:27 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_heweather, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/root/BOT_Q/bot_linux/bot.py", line 69, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
  File "/usr/local/python3.9/lib/python3.9/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/usr/local/python3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_heweather/__init__.py", line 51, in _
    img = await render(w_data)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_heweather/render_pic.py", line 11, in render
    return await template_to_pic(
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/date_source.py", line 194, in template_to_pic
    return await html_to_pic(
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/date_source.py", line 158, in html_to_pic
    async with get_new_page(**kwargs) as page:
  File "/usr/local/python3.9/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_htmlrender/browser.py", line 46, in get_new_page
    page = await browser.new_page(**kwargs)
TypeError: new_page() got an unexpected keyword argument 'base_url'

**Comment by kexue-z** [comment]
提供一下nonebot2 playwright htmlrender 和 heweather的版本
