### ISSUE TITLE
查询出错 api已经设置

### ISSUE THREAD

**Issue by Arturia169** [kexue-z/nonebot-plugin-heweather#20]
![image](https://user-images.githubusercontent.com/69199123/169482701-cd6b4997-cda9-4d4c-818d-da5ec452c7de.png)
![image](https://user-images.githubusercontent.com/69199123/169482750-22bf25df-7fc5-4d39-b236-fb91583fdd76.png)

**Comment by kexue-z** [comment]
查询哪里的状态 是国外的吗

可以将 log level 设置为debug看看api获取情况

**Comment by kexue-z** [comment]
fixed at https://github.com/kexue-z/nonebot-plugin-heweather/commit/1d3eca4f025df99b810d7c76519e08eb6085dee1
