### ISSUE TITLE
每天都需要重启服务才行

### ISSUE THREAD

**Issue by chung1912** [kexue-z/nonebot-plugin-heweather#21]
报错提示如下
playwright._impl._api_types.Error
Target page, context or browser has been closed

**Comment by kexue-z** [comment]
什么系统 干了什么 盲猜是用了什么一键优化把playwright杀了

**Comment by kexue-z** [comment]
浏览器程序被杀了 建议使用单独的环境运行 如docker等 或者使用python虚拟环境 如 poetry 等。

小心使用各种内存清理软件
