### ISSUE TITLE
无法获取天气

### ISSUE THREAD

**Issue by GC-ZF** [kexue-z/nonebot-plugin-heweather#24]
发送北京天气返回错误信息
![image](https://user-images.githubusercontent.com/94956933/174700058-f6270c63-b5af-4951-8497-d8eb876c2977.png)
![image](https://user-images.githubusercontent.com/94956933/174700085-f5e79661-2011-4660-9756-2b5e6b71bdc7.png)
config.py配置
![image](https://user-images.githubusercontent.com/94956933/174700150-5cafba77-5201-41b3-bf73-a5ee1e7f959d.png)

**Comment by kexue-z** [comment]
？

**Comment by GC-ZF** [comment]
> ？

解决了，但是具体不知道哪错了。我有时候不是开VPN么，我猜可能是网络问题，但是我确定我刚才关了，一直返回那些报错，然后我在命令行把网络缓存刷了一下`ipconfig/flushdns`，然后自己就好了
