### ISSUE TITLE
[bug] 歪国天气无法查询

### ISSUE THREAD

**Issue by Lu-Qi-777** [kexue-z/nonebot-plugin-heweather#25]
weather_data.py 126行
Weather类中的_air方法
在获取外国的空气质量时，请求返回的response虽然status_code是200，但其中内容只有{'code': '403'}
在return的时候会报错

图片是用东京（location=65E77）去请求空气质量的结果，我用的是普通版 API
![1](https://user-images.githubusercontent.com/21366357/175501261-48e43a37-2a08-40a9-bb65-323fe41435be.png)

**Comment by kexue-z** [comment]
这个好像已经修复了 看看什么版本的插件

**Comment by Lu-Qi-777** [comment]
> 这个好像已经修复了 看看什么版本的插件

检查了一下，确实是拉取的最新版本代码
目前插件确实是支持无air下绘制最终结果图，只要`if weather.air`为假就行
但目前报错的原因是response过来的内容里没有now字段，`AirApi(**res.json())`只接收到了code
（或许以前没有air信息会返回{‘code’:xxx, ‘now’:"}，现在改了？）
![2](https://user-images.githubusercontent.com/21366357/175752786-c90f8da9-a521-44e9-88a9-6c764a4a8121.png)

**Comment by Lu-Qi-777** [comment]
对了，还有个建议顺便再这个issues里提一下吧←_←
生成图片时，地点名`self.city_name`是用户触发命令时候的内容
测试用wuhan这种拼音，11.4,51.4这种经纬度；通过和风的API也能获取到对应的数据
可以考虑在`_get_city_id`方法里顺便把`res["location"][0]["name"]`也返回并更新给`self.city_name`

**Comment by kexue-z** [comment]
fix at https://github.com/kexue-z/nonebot-plugin-heweather/commit/98781291c2c1205367ddd25456e81a4b9f466360
