### ISSUE TITLE
Failed to import "nonebot_plugin_heweather"

### ISSUE THREAD

**Issue by Ble55me** [kexue-z/nonebot-plugin-heweather#26]
![bug](https://user-images.githubusercontent.com/98486039/176206706-9e592ea3-f648-4a43-94c3-0fe704cfec87.png)
好像是APIKEY填写的不大对劲，麻烦大佬看看哪里出了问题

**Comment by kexue-z** [comment]
？

**Comment by Ble55me** [comment]
是哪里填的出了问题吗

**Comment by kexue-z** [comment]
哪里都有问题 你填的地方就不对劲

**Comment by Viktor-01** [comment]
是不是 apikey 没加双引号？

**Comment by kexue-z** [comment]
是不是应该写到 `.env` 里呢
