### ISSUE TITLE
请问这种情况如何调整字体？

### ISSUE THREAD

**Issue by sakamataz** [kexue-z/nonebot-plugin-heweather#27]
![1910148424-1869719204-1A397259A0739BB8F9D4B807A8455462](https://user-images.githubusercontent.com/44469959/176939193-6bb302c2-8eb6-4235-ab36-4c3bb9df092f.png)

**Comment by sakamataz** [comment]
之前本来是正常的，执行了如下指令。但是应该也不是中文字体缺失的问题
sudo apt install fonts-noto
sudo locale-gen zh_CN zh_CN.UTF-8
sudo update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
fc-cache -fv

**Comment by kexue-z** [comment]
css没了

**Comment by sakamataz** [comment]
CSS文件在服务器下存在，应该不是这个的问题

**Comment by kexue-z** [comment]
不知道怎么复现 暂置

**Comment by kexue-z** [comment]
htmlrender 的问题 会退版本到 `0.0.5`

https://github.com/kexue-z/nonebot-plugin-heweather/issues/28#issuecomment-1185409571
