### ISSUE TITLE
【显示错误】

### ISSUE THREAD

**Issue by Agnes4m** [kexue-z/nonebot-plugin-heweather#28]
python3.9.12,nonebot2=2.0.0b4，htmlrender也装了
之前还正常的，不知道哪次更新后就这样了,。

![image](https://user-images.githubusercontent.com/70925546/178171406-7bfe946d-0b34-4ddd-b3b1-9f9c39cc4c78.png)

**Comment by lancer-wang** [comment]
+1

**Comment by kexue-z** [comment]
怎么复现 说说

**Comment by lancer-wang** [comment]
> 怎么复现 说说

感觉是和火狐浏览器的兼容有关,ubuntu默认用的是firefox

**Comment by lancer-wang** [comment]
browser.py 在nonebot-plugin-htmlrender 0.1.0版本改成了win用谷歌,linux用firefox
0,0,5一致是谷歌,我刚才装了0.0.5,样式就正常了
async def launch_browser(**kwargs) -> Browser:
    assert _playwright is not None, "Playwright is not initialized"
    if "win" in platform.lower():
        return await _playwright.chromium.launch(**kwargs)
    else:
        return await _playwright.firefox.launch(**kwargs)
![image](https://user-images.githubusercontent.com/69783837/179190347-22ef080a-badd-4b8d-b5b1-e1498d3e43c2.png)


> 怎么复现 说说

**Comment by kexue-z** [comment]
确实有这个可能 不过按道理说是不影响的

我在Mac上用了nonebot-plugin-htmlrender 0.1.0 是没有问题的

**Comment by kexue-z** [comment]
暂时先把 `nonebot-plugin-htmlrender `改为 `0.0.5` 运行

**Comment by GC-ZF** [comment]
版本已回退，插个眼，等好了回来更新
