### ISSUE TITLE
显示问题，猜测找不到路径或者路径不生效

### ISSUE THREAD

**Issue by saferabbit** [kexue-z/nonebot-plugin-heweather#31]
![TBL}B(@_OY`4~2ES2PH24NT](https://user-images.githubusercontent.com/44218328/191925214-4f9caa5c-d23f-450d-bdfa-fc0595d25182.PNG)
无论我安装哪个版本都显示不了样式。我试着把外联改成内联，样式正常了，但是识别不到字体文件。

**Comment by kexue-z** [comment]
字体这个不是本地的资源来着

**Comment by saferabbit** [comment]
。。。我PIP安装了nonebot-plugin-htmlrender后就正常，可以close了
