### ISSUE TITLE
超时？

### ISSUE THREAD

**Issue by Admsec** [kexue-z/nonebot-plugin-heweather#35]
![image](https://user-images.githubusercontent.com/86643414/200272234-ca417f08-c760-4075-ad48-4fa475ed43b0.png)
具体的就显示这样了，似乎其他的都正常，但是就是显示超时

**Comment by kexue-z** [comment]
建议使用pm2或screen来运行bot。另外，使用poetry、pipx等管理虚拟环境会更好。

实在不行，就用docker吧

PS：以上内容自行学习~

**Comment by Admsec** [comment]
我用的环境就是 potry 环境，然后这个是为了方便看日志。这个插件没有问题，但是就是显示插件超时了，请问一下那个插件超时可以自定义的吗？

**Comment by kexue-z** [comment]
按道理超时只有资源文件找不到才会出现。
检查一下样式和图标能不能访问？
因为这边其他人并没有出现问题。

亦或者，使用 `https://github.com/noneplugin/nonebot-plugin-shindan` 试试，他也是用的`htmlrender`

**Comment by Admsec** [comment]
用 https://github.com/noneplugin/nonebot-plugin-shindan 还是提示同样的错误，我觉得应该是我的 Playwright 有问题

**Comment by Admsec** [comment]
我在 .env.prod 里面增加了一行 htmlrender_browser = 'firefox' 让它去下载 firefox ，然后就解决了
![image](https://user-images.githubusercontent.com/86643414/200458364-955d2c18-f5fa-46c1-9cc9-912833bc456c.png)

**Comment by kexue-z** [comment]
彳亍
