### ISSUE TITLE
日志正常打印 但是没天气情况发送

### ISSUE THREAD

**Issue by yangy666** [kexue-z/nonebot-plugin-heweather#38]
12-08 14:07:16 [SUCCESS] nonebot | OneBot V11 1251746795 | [message.private.friend]: Message -1639878524 from 303******* "#天气"
12-08 14:07:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_heweather)
12-08 14:07:16 [INFO] nonebot_plugin_heweather | 使用个人开发版API
12-08 14:07:16 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_heweather) running complete

**Comment by KomoriDev** [comment]
我也遇到这个情况

**Comment by kexue-z** [comment]
是不是bot端被风控还是什么情况，抑或是浏览器崩溃了，建议nb看看debug日志，gocq也看看
