### ISSUE TITLE
部署后 系统找不到指定的模块

### ISSUE THREAD

**Issue by DragonSauce** [kexue-z/nonebot-plugin-heweather#44]
![7EY8 3W06W)T9}UZ`V~$TTB](https://user-images.githubusercontent.com/42651551/226151548-7b249248-8acd-40c3-941d-158ed1fb93f5.png)
![SAV5~W~`97ZI5DEOVL `4VB](https://user-images.githubusercontent.com/42651551/226151553-328f476c-3e02-46b3-9634-37835617907b.png)

**Comment by kexue-z** [comment]
更新一下最新的 `v0.6.3`

**Comment by DragonSauce** [comment]
如何更新

**Comment by DragonSauce** [comment]
![7EY8 3W06W)T9}UZ`V~$TTB](https://user-images.githubusercontent.com/42651551/226153856-8e44810d-96db-469e-8b63-3c3dd3b9c173.png)

**Comment by kexue-z** [comment]
？你怎么装的就怎么更新啊

**Comment by kexue-z** [comment]
pip install msvc-runtime

**Comment by DragonSauce** [comment]
nb 那边已经更新了 本地是没问题de，上了服务器才这样

**Comment by DragonSauce** [comment]
好的 正常了
