### ISSUE TITLE
云崽bot是否可以运行此插件

### ISSUE THREAD

**Issue by admimare** [kexue-z/nonebot-plugin-heweather#55]
报错如下附件
[新建 文本文档 (4).txt](https://github.com/kexue-z/nonebot-plugin-heweather/files/12269818/4.txt)
请问该如何解决

**Comment by admimare** [comment]
调用的路径下的两个文件
[py.txt](https://github.com/kexue-z/nonebot-plugin-heweather/files/12269821/py.txt)
[message.txt](https://github.com/kexue-z/nonebot-plugin-heweather/files/12269827/message.txt)

**Comment by kexue-z** [comment]
不支持。暂时没有能力适配。

欢迎PR

**Comment by admimare** [comment]
> 
好的 感谢
