### ISSUE TITLE
报错1 validation error for NowApi now

### ISSUE THREAD

**Issue by huangzhitian** [kexue-z/nonebot-plugin-heweather#64]
![image](https://github.com/kexue-z/nonebot-plugin-heweather/assets/129321746/5bb48b38-1cb0-417c-8598-71e12e3d3f00)
![image](https://github.com/kexue-z/nonebot-plugin-heweather/assets/129321746/1a1f4489-afb5-45b7-a797-93991d907b5d)

**Comment by kexue-z** [comment]
盲猜免费版，然后你用了标准订阅的方式，不匹配肯定炸

**Comment by huangzhitian** [comment]
> 盲猜免费版，然后你用了标准订阅的方式，不匹配肯定炸

都试过

**Comment by kexue-z** [comment]
所以你到底用的什么订阅的？建议截个图看看

**Comment by lintonxue00** [comment]
今天我也遇到了这个问题，我自己是实名认证的个人开发者模式，以前是可以用QWEATHER_APITYPE = 1 但是最近不可以用了，好像官网现在标准版也需要收费了，所以现在只能用的就是免费版了。

**Comment by lintonxue00** [comment]
现在用标准订阅至少需要充值10块钱才让你用。

**Comment by lintonxue00** [comment]
之前申请个人开发者可以让你免费使用7天标准版，现在这个福利被阉割了，
现在只允许给你使用的是免费版12小时内的订阅，除非充钱。

![image](https://github.com/kexue-z/nonebot-plugin-heweather/assets/115356968/690702ea-4019-43ff-b662-08c2e668cc35)

**Comment by lintonxue00** [comment]
![image](https://github.com/kexue-z/nonebot-plugin-heweather/assets/115356968/19f60e4c-ea70-4f6a-b5e7-a5074e23fade)
免费订阅可以3-7天为什么现在只能3天呀，我自己是申请个人开发者的

**Comment by kexue-z** [comment]
可以加一个修改天数的功能

**Comment by kexue-z** [comment]
已经添加修改天数的功能了
