### ISSUE TITLE
在使用了标准订阅的情况下，bot仍然只输出3天天气预报

### ISSUE THREAD

**Issue by BCMonomial** [kexue-z/nonebot-plugin-heweather#70]
已确认 `QWEATHER_APITYPE = 1`，API Key调用正常，和风天气订阅状况正常，后台查询发现所有的调用都是3日天气预报而不是7日
![image](https://github.com/user-attachments/assets/7c2a89b9-4603-4bfa-af85-77726e96c194)
![de45a675c5c380636d8dba5a22505a92](https://github.com/user-attachments/assets/cc8259d3-67b5-4f04-99dd-fb0ce5e99ffd)

**Comment by kexue-z** [comment]
设置 `QWEATHER_FORECASE_DAYS`

**Comment by BCMonomial** [comment]
已解决
